# Generated by Django 2.1.7 on 2019-04-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyQueryManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Faculty', max_length=255)),
                ('quantumTime', models.IntegerField(default=0)),
                ('time', models.TimeField(auto_now=True)),
                ('noOfProcess', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arrivalTime', models.IntegerField(default=0)),
                ('burstTime', models.IntegerField(default=0)),
                ('completionTime', models.IntegerField(default=0)),
                ('remainingTime', models.IntegerField(default=0)),
                ('waitingTime', models.IntegerField(default=0)),
                ('turnAroundTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentQueryManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Faculty', max_length=255)),
                ('quantumTime', models.IntegerField(default=0)),
                ('time', models.TimeField(auto_now=True)),
                ('noOfProcess', models.IntegerField()),
            ],
        ),
    ]
