# Generated by Django 2.1.7 on 2019-04-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundRobin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyQueryManagement',
        ),
        migrations.DeleteModel(
            name='StudentQueryManagement',
        ),
        migrations.AddField(
            model_name='process',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='arrivalTime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='burstTime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='completionTime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='remainingTime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='turnAroundTime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='waitingTime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
