# Generated by Django 2.1.7 on 2019-04-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoundRobin', '0004_auto_20190410_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='QunatumTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantumTime', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
